project:
  type: website
  output-dir: docs
  render:
   - "*.qmd"
   - "!slides/*"

website:
  title: "Creative Coding"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - getting-started.qmd
      - truchet-tiles.qmd
      - about.qmd
  margin-header: |
    ![](/images/ANU_Secondary_Horizontal_GoldBlack.png)

format:
  html:
    css: styles.css
    toc: true



